### ISSUE TITLE
--dzをつけるとRictyDiscordが文字化けする

### ISSUE THREAD

**Issue by aucfan-kori** [sanemat/homebrew-font#17]
![2014-10-08 14 57 27](https://cloud.githubusercontent.com/assets/8587594/4554530/01012c56-4eb0-11e4-843c-6ee63fb2af9a.png)
![2014-10-08 14 56 59](https://cloud.githubusercontent.com/assets/8587594/4554527/f200f740-4eaf-11e4-80c5-cc8db6c3f7ca.png)

**Comment by aikinai** [comment]
Ricty の `ricty_discord_patch.pe` が Inconsolata-dz に対応していなく、Inconsolata の特定の符号点をコピーしているから発生します。 #27 で Inconsolata-dz にも対応するように `ricty_discord_patch.pe` へのパッチを加えました。
