### ISSUE TITLE
fontpatcher SHA1 mismatch

### ISSUE THREAD

**Issue by m-nagae** [sanemat/homebrew-font#31]
brew reinstall --powerline ricty
==> Reinstalling sanemat/font/ricty with --vim-powerline, --powerline
==> Downloading https://github.com/yascentur/Ricty/archive/3.2.4.tar.gz
==> Downloading from: https://codeload.github.com/yascentur/Ricty/tar.gz/3.2.4
Already downloaded: /Library/Caches/Homebrew/ricty-3.2.4.tar.gz
==> Downloading http://sourceforge.jp/frs/redir.php?m=iij&f=%2Fmix-mplus-ipa%2F59022%2Fmigu-1m-20130617.zip
==> Downloading from: http://iij.dl.sourceforge.jp/mix-mplus-ipa/59022/migu-1m-20130617.zip
Already downloaded: /Library/Caches/Homebrew/ricty--migu1mfonts-20130617.zip
==> Downloading https://github.com/powerline/fontpatcher/archive/18a788b8ec1822095813b73b0582a096320ff714.zip
==> Downloading from: https://codeload.github.com/powerline/fontpatcher/zip/18a788b8ec1822095813b73b0582a096320ff714
Already downloaded: /Library/Caches/Homebrew/powerline-20150113.zip
Error: SHA1 mismatch
Expected: eacbca3a3e3b7acd03743e80a51de97c9c0bbc80
Actual: 08cbd82a0b058af4ed2e03cd0ed2fbcf1f14a0c3
Archive: /Library/Caches/Homebrew/powerline-20150113.zip
To retry an incomplete download, remove the file above.

**Comment by aikinai** [comment]
This should be fixed now.
Let me know if you have any problems!
