### ISSUE TITLE
can't find resource "glib--patch" install failed(OS X 10.11)

### ISSUE THREAD

**Issue by kaku87** [sanemat/homebrew-font#34]
Download failed: https://gist.githubusercontent.com/jacknagel/af332f42fae80c570a77/raw/7b5fd0d2e6554e9b770729fddacaa2d648327644/glib-hardcoded-paths.diff

**Comment by aikinai** [comment]
I was going to look into cleaning up open issues, but I'm not sure what this means. Can you explain how you got this error?

**Comment by equal-l2** [comment]
Since the gist has been removed, we cannot know about the problem anymore, closing.
