### ISSUE TITLE
Ricty download fails due to move

### ISSUE THREAD

**Issue by limitusus** [sanemat/homebrew-font#35]
Ricty site looks moved to http://www.rs.tus.ac.jp/yyusa/ricty.html, so the Ricty archive download fails.

**Comment by sanemat** [comment]
Good catch!

**Comment by aikinai** [comment]
I was just about to update the version of Ricty and the base fonts, so I can fix this. I actually have the commit ready, I just wanted to test a little more before pushing.

**Comment by limitusus** [comment]
@aikinai 
Does it really fix this problem?
I retried but failed.

Actually I tested the zip file URL in #36 but received 404.

```
%  brew install ricty
==> Installing ricty from sanemat/font
==> Downloading https://github.com/yascentur/Ricty/archive/4.0.1.zip
==> Downloading from https://codeload.github.com/yascentur/Ricty/zip/4.0.1

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "ricty"
Download failed: https://codeload.github.com/yascentur/Ricty/zip/4.0.1
```

```
%  wget -v https://github.com/yascentur/Ricty/archive/4.0.1.zip
--2016-07-05 16:11:42--  https://github.com/yascentur/Ricty/archive/4.0.1.zip
Resolving github.com... 192.30.253.112
Connecting to github.com|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/yascentur/Ricty/zip/4.0.1 [following]
--2016-07-05 16:11:43--  https://codeload.github.com/yascentur/Ricty/zip/4.0.1
Resolving codeload.github.com... 192.30.253.120
Connecting to codeload.github.com|192.30.253.120|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-07-05 16:11:44 ERROR 404: Not Found.
```

BRs,

**Comment by aikinai** [comment]
Oh, you're right! It moved just now after I already put together my commit a few days ago. And it worked when I was testing since it was still in my Homebrew cache. I'll update it again.

**Comment by aikinai** [comment]
Okay, it should work now. Let me know if you still have an issue.

**Comment by limitusus** [comment]
Confirmed and it succeeds by specifying direct URL to `ricty.rb`.
```
%  brew install https://raw.github.com/sanemat/homebrew-font/master/ricty.rb
######################################################################## 100.0%
==> Downloading http://www.rs.tus.ac.jp/yyusa/ricty/ricty_generator.sh
(snip)
```
Thanks!

**Comment by koji-1009** [comment]
Hi, thanks for maintaining this repository.

Perhaps the Ricty's homepage is moved.
before : <http://yusa.lab.uec.ac.jp/~yusa/ricty.html>
after : <https://rictyfonts.github.io/>, <https://github.com/rictyfonts/rictyfonts.github.io>
