### ISSUE TITLE
The Discord version have some strange faces

### ISSUE THREAD

**Issue by delphinus** [sanemat/homebrew-font#46]
<img width="288" alt="2017-01-01 21 11 20" src="https://cloud.githubusercontent.com/assets/1239245/21581148/001fed14-d067-11e6-8fcf-6dafa2c787a1.png">

In the picture above, it shows `r` and `0` glyphs change to `~` & `^`. The regular version is correct.

I noticed this on working in #33, but this can be reproduced in the latest master.

**Comment by equal-l2** [comment]
Well, this is a known problem. (See #43)

I don't know which is worse, huge " i " & " j " & " 0 " or incorrect character.

**Comment by equal-l2** [comment]
If upstream fix not come in a couple days, maybe I will revert ricty script to former version.

**Comment by equal-l2** [comment]
This seems to be a problem of homebrew's fontforge, not of ricty_generator.
(This problem doesn't occur with official binary)

**Comment by equal-l2** [comment]
I made a issue on fontforge.
fontforge/fontforge#2984

**Comment by equal-l2** [comment]
The problem has solved with 23fe763 .

This issue remain open because fontforge bug is not solved yet.

**Comment by delphinus** [comment]
Thanks! I confirmed the bug solved.
