### ISSUE TITLE
Latest fontforge (20170731) segfaults when running ricty_generator

### ISSUE THREAD

**Issue by aikinai** [sanemat/homebrew-font#49]
I'm getting this error when I try to install Ricty today:

    ./ricty_generator-4.1.0.sh: line 1042: 67291 Segmentation fault: 11  $fontforge_command -script ${tmpdir}/${ricty_generator} 2> $redirection_stderr

It seems to be a bug in the latest Fontforge, so I manually reverted to the [previous version of Fontforge](https://github.com/Homebrew/homebrew-core/blob/d1dfe7b506da542c8828ebd775a1f4f943e55ed7/Formula/fontforge.rb) with `brew edit fontforge` (just copied and pasted the old formula). It's very hacky and I don't know if it's even possible to add this officially to the Ricty formula, but I just wanted to share the hacky solution here in case other people run into the same issue.

**Comment by sanemat** [comment]
Segmentation fault :crying_cat_face: 
Thank you for sharing.

**Comment by equal-l2** [comment]
This issue occurs only with Homebrew fontforge.
In other word, you can successfully build with official build of fontforge.

**Comment by equal-l2** [comment]
The issue seems to have been solved by https://github.com/Homebrew/homebrew-core/commit/32a044470d7e80aa254cbd174555e5ff0e1aab4e.
Feel free to reopen if it still occurs.
