### ISSUE TITLE
Error due to missing ricty_generator-4.1.0.sh

### ISSUE THREAD

**Issue by tororu-s** [sanemat/homebrew-font#51]
Since "http://www.rs.tus.ac.jp/yyusa/ricty.html" cannot be accessed, an error occurs during brew install.

**Comment by equal-l2** [comment]
The author transferred to the other university and the homepage in the previous is removed.

http://kjk.office.uec.ac.jp/Profiles/76/0007581/profile.html

**Comment by equal-l2** [comment]
Can someone contact him to distribute the script again?
I'm busy and no time to do that now...

**Comment by hirose504** [comment]
Ricty has moved to new homepage.

http://www.yusa.lab.uec.ac.jp/~yusa/ricty.html
http://www.yusa.lab.uec.ac.jp/~yusa/ricty/ricty_generator.sh

**Comment by equal-l2** [comment]
Thank you!
I'll update the formula soon.
